-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtwIhHs0OcNz/+6p2
M+s4mVBjJ4n58kuA36dffy+Qi/SgCgYIKoZIzj0DAQehRANCAAQJ6WauMeL4wlsS
FtgRz2q4jDtjeENWfMQdGbbifNIY34XD4N7rSZvaTdgcjdedGj7ftMqLd+tndxCX
muNAtwkk
-----END PRIVATE KEY-----