// Server-side BlackjackEngine for secure game validation
import { randomInt } from "crypto";

export interface Card {
  suit: "hearts" | "diamonds" | "clubs" | "spades";
  value: string;
  numericValue: number;
}

export interface GameResult {
  playerTotal: number;
  dealerTotal: number;
  playerHand: Card[];
  dealerHand: Card[];
  result: "win" | "lose" | "push";
  isPlayerBlackjack: boolean;
  isDealerBlackjack: boolean;
  playerBusted: boolean;
  dealerBusted: boolean;
}

export class ServerBlackjackEngine {
  /**
   * Validates that the cards are legitimate playing cards
   */
  static validateCard(card: Card): boolean {
    const validSuits = ["hearts", "diamonds", "clubs", "spades"];
    const validValues = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
    
    if (!validSuits.includes(card.suit)) return false;
    if (!validValues.includes(card.value)) return false;
    
    // Validate numeric value matches the card value
    const expectedNumeric = card.value === "A" ? 11 : 
                           ["J", "Q", "K"].includes(card.value) ? 10 : 
                           parseInt(card.value);
    
    return card.numericValue === expectedNumeric;
  }

  /**
   * Validates a hand contains only valid cards and has reasonable count
   */
  static validateHand(hand: Card[]): boolean {
    if (!Array.isArray(hand) || hand.length < 2 || hand.length > 10) {
      return false;
    }
    
    return hand.every(card => this.validateCard(card));
  }

  /**
   * Calculates the total value of a hand, properly handling Aces
   */
  static calculateTotal(hand: Card[]): number {
    let total = 0;
    let aces = 0;

    for (const card of hand) {
      if (card.value === "A") {
        aces++;
        total += 11;
      } else {
        total += card.numericValue;
      }
    }

    // Adjust for aces (count as 1 instead of 11 if needed)
    while (total > 21 && aces > 0) {
      total -= 10;
      aces--;
    }

    return total;
  }

  /**
   * Determines if a hand is a blackjack (21 with exactly 2 cards)
   */
  static isBlackjack(hand: Card[]): boolean {
    return hand.length === 2 && this.calculateTotal(hand) === 21;
  }

  /**
   * Determines the winner of a blackjack game based on validated hands
   */
  static determineWinner(
    playerHand: Card[],
    dealerHand: Card[]
  ): GameResult {
    // Validate inputs
    if (!this.validateHand(playerHand) || !this.validateHand(dealerHand)) {
      throw new Error("Invalid card hands provided");
    }

    const playerTotal = this.calculateTotal(playerHand);
    const dealerTotal = this.calculateTotal(dealerHand);
    
    const playerBusted = playerTotal > 21;
    const dealerBusted = dealerTotal > 21;
    
    const isPlayerBlackjack = this.isBlackjack(playerHand);
    const isDealerBlackjack = this.isBlackjack(dealerHand);

    let result: "win" | "lose" | "push";

    // Determine result using standard blackjack rules
    // CRITICAL: Player bust is an immediate loss, regardless of dealer's hand
    if (playerBusted) {
      result = "lose";
    } 
    // If player didn't bust but dealer did, player wins
    else if (dealerBusted) {
      result = "win";
    } 
    // Both players have valid hands (no busts), check for blackjacks
    else if (isPlayerBlackjack && isDealerBlackjack) {
      result = "push";
    } else if (isPlayerBlackjack) {
      result = "win";
    } else if (isDealerBlackjack) {
      result = "lose";
    } 
    // Compare totals for normal hands
    else if (playerTotal > dealerTotal) {
      result = "win";
    } else if (playerTotal < dealerTotal) {
      result = "lose";
    } else {
      // Only push when both have same total AND neither busted
      result = "push";
    }

    return {
      playerTotal,
      dealerTotal,
      playerHand,
      dealerHand,
      result,
      isPlayerBlackjack,
      isDealerBlackjack,
      playerBusted,
      dealerBusted
    };
  }

  /**
   * Internal defensive assertion — the dealer hand is now always server-generated by
   * dealDealerTurn() below, never submitted by a client, so this just guards against a bug
   * in that loop rather than validating external input.
   */
  static validateDealerPlay(dealerHand: Card[]): boolean {
    const total = this.calculateTotal(dealerHand);
    return total >= 17 || total > 21;
  }

  /**
   * Builds a fresh, shuffled 52-card deck. Fisher-Yates shuffle using crypto.randomInt() —
   * unpredictable even to an attacker observing many outcomes, unlike Math.random().
   */
  static createShuffledDeck(): Card[] {
    const suits: Card["suit"][] = ["hearts", "diamonds", "clubs", "spades"];
    const values = [
      { value: "A", numeric: 11 },
      { value: "2", numeric: 2 },
      { value: "3", numeric: 3 },
      { value: "4", numeric: 4 },
      { value: "5", numeric: 5 },
      { value: "6", numeric: 6 },
      { value: "7", numeric: 7 },
      { value: "8", numeric: 8 },
      { value: "9", numeric: 9 },
      { value: "10", numeric: 10 },
      { value: "J", numeric: 10 },
      { value: "Q", numeric: 10 },
      { value: "K", numeric: 10 },
    ];

    const deck: Card[] = [];
    for (const suit of suits) {
      for (const val of values) {
        deck.push({ suit, value: val.value, numericValue: val.numeric });
      }
    }

    for (let i = deck.length - 1; i > 0; i--) {
      const j = randomInt(i + 1);
      [deck[i], deck[j]] = [deck[j], deck[i]];
    }

    return deck;
  }

  /**
   * Single standard dealer rule for every real-money mode — no per-mode branching, no
   * Math.random(). S17: dealer stands on all 17s (hard and soft), hits below 17.
   */
  static shouldDealerHit(dealerHand: Card[]): boolean {
    return this.calculateTotal(dealerHand) < 17;
  }

  /**
   * Deals out the dealer's turn against an already-decided-complete set of player hands,
   * mutating and returning the given deck/dealerHand by reference (caller owns persisting them).
   */
  static dealDealerTurn(deck: Card[], dealerHand: Card[]): void {
    while (this.shouldDealerHit(dealerHand)) {
      const card = deck.pop();
      if (!card) throw new Error("Deck exhausted during dealer turn");
      dealerHand.push(card);
    }
  }
}